name: Android Monkey
on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron:  '0 5 * * *' # Once per day at 05:00 UTC

jobs:
  precondition:
    runs-on: ubuntu-latest
    name: Check preconditions
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 1000 # fetch month or so

      - name: Check that Android was updated
        id: check
        shell: bash
        run: |
          DIRS="android base drape drape_frontend editor ge0 map platform routing search shaders storage traffic transit"
          if [ '${{ github.event_name }}' != 'schedule' ] || 
             [ $(git rev-list --count --since="24 hours" HEAD $DIRS) -gt 0 ]; then
            echo "::set-output name=updated::true"
          else
            echo "::set-output name=updated::"
          fi
    outputs:
      updated: ${{ steps.check.outputs.updated }}

  android-google-debug:
    name: Android Google Debug
    runs-on: ubuntu-latest
    needs: precondition
    if: ${{ needs.precondition.outputs.updated != '' }}
    environment: beta
    steps:
      - name: Install build tools and dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Google SDK
        uses: google-github-actions/setup-gcloud@master

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 100 # enough to get all commits for the current day

      - name: Parallel submodules checkout
        shell: bash
        run: git submodule update --init --recursive --jobs=$(($(nproc) * 2))

      - name: Checkout private keys
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
          ref: master
          path: private.git

      - name: Configure repo with private keys
        shell: bash
        run: |
          ./configure.sh ./private.git
          rm -rf ./private.git

      - name: Set up SDK
        shell: bash
        run: (cd tools/android; ./set_up_android.py --sdk $ANDROID_SDK_ROOT)

      - name: Compile
        shell: bash
        working-directory: android
        run: |
          cmake --version
          ninja --version
          ./gradlew -Parm64 -Parm32 -Pfirebase assembleGoogleDebug

      - name: Run monkey
        run: |
          gcloud auth activate-service-account --key-file android/firebase-test-lab.json
          gcloud config set project omapsapp
          gcloud firebase test android run --app ./android/build/outputs/apk/google/debug/OrganicMaps-*-google-debug.apk \
            --device model=redfin,version=30 \
            --device model=a10,version=29 \
            --device model=dipper,version=28 \
            --device model=OnePlus3T,version=26 \
            --device model=flo,version=21,orientation=landscape \
            --timeout 15m
